apiVersion: v2
type: application
name: readur
home: https://github.com/readur/readur
icon: https://github.com/readur/readur/blob/main/assets/icon.png
deprecated: false
description: |-
  Readur is a document management and OCR processing service that automatically processes uploaded documents, extracts text using OCR, and makes content searchable.
annotations:
  category: Document Management
version: 0.1.3
appVersion: latest
kubeVersion: ">= 1.19"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 3.7.3
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.13
    condition: postgresql.enabled
keywords:
  - document-management
  - ocr
  - text-extraction
  - file-processing
  - rust
  - self-hosted
  - document-search
  - pdf
  - tesseract
maintainers:
  - name: readur
    url: https://github.com/readur/readur
sources:
  - https://github.com/readur/readur
