## This chart relies on the common library chart from bjw-s
## You can find it and the values you can provide and modify, at https://github.com/bjw-s/helm-charts/blob/common-3.3.2/charts/library/common/values.yaml
## Refer there for more detail about the supported values.
## Any values that you find in the above `values.yaml` can be provided to this chart and are then rendered.

controllers:
  main:
    containers:
      readur:
        image:
          repository: readur/readur
          tag: latest
          pullPolicy: IfNotPresent
        env:
          # Server Configuration
          SERVER_HOST: "0.0.0.0"
          SERVER_PORT: "8000"

          # File Management
          UPLOAD_PATH: "/app/uploads"
          WATCH_FOLDER: "/app/watch"
          ALLOWED_FILE_TYPES: "pdf,txt,doc,docx,png,jpg,jpeg"
          MAX_FILE_SIZE_MB: "50"
          MAX_FILE_AGE_HOURS: "24"

          # OCR Settings
          OCR_LANGUAGE: "eng"
          CONCURRENT_OCR_JOBS: "4"
          OCR_TIMEOUT_SECONDS: "300"

          # Performance
          MEMORY_LIMIT_MB: "512"
          CPU_PRIORITY: "normal"

          # File Watching
          WATCH_INTERVAL_SECONDS: "30"
          FILE_STABILITY_CHECK_MS: "1000"

persistence:
  uploads:
    enabled: true
    type: persistentVolumeClaim
    storageClass:
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /app/uploads

  watch:
    enabled: true
    type: persistentVolumeClaim
    storageClass:
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /app/watch

service:
  main:
    controller: main
    enabled: true
    ports:
      http:
        port: 8000
        targetPort: 8000

ingress:
  main:
    enabled: false
    className: nginx
    annotations:
      # proxy-body-size is set to 100m to match Nginx config
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    hosts:
      - host: readur.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls: []
