#!/usr/bin/env bash
#
# Regenerates the frontend API types in frontend/src/types/generated from the
# Rust models, using ts-rs.
#
# Every type that derives `ts_rs::TS` with `#[ts(export)]` gets an
# `export_bindings_*` test; running those tests writes one `.ts` file per type
# into TS_RS_EXPORT_DIR (set in .cargo/config.toml). This script clears the old
# output, runs only those tests, then writes a sorted `index.ts` barrel.
#
# Hosts without the OCR system libraries (leptonica, tesseract, libclang,
# openssl) can build inside a nix-shell: set READUR_USE_NIX=1. CI and hosts
# that have the libraries installed run plain `cargo`.
#
# Usage: scripts/generate-ts-bindings.sh
#        READUR_USE_NIX=1 scripts/generate-ts-bindings.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/frontend/src/types/generated"

run_cargo() {
    if [ "${READUR_USE_NIX:-0}" = "1" ]; then
        if ! command -v nix-shell >/dev/null 2>&1; then
            echo "READUR_USE_NIX=1 but nix-shell is not on PATH" >&2
            exit 1
        fi
        local args
        args="$(printf '%q ' "$@")"
        nix-shell -p pkg-config leptonica tesseract libclang openssl --run "
set -euo pipefail
export LIBCLANG_PATH=\$(nix-build --no-out-link '<nixpkgs>' -A libclang.lib)/lib
GLIBC_DEV=\$(nix-build --no-out-link '<nixpkgs>' -A glibc.dev)
CLANG_LIB=\$(nix-build --no-out-link '<nixpkgs>' -A llvmPackages.clang-unwrapped.lib)
export BINDGEN_EXTRA_CLANG_ARGS=\"-isystem \$(echo \$CLANG_LIB/lib/clang/*/include) -isystem \$GLIBC_DEV/include\"
export LD_LIBRARY_PATH=\"\$(nix-build --no-out-link '<nixpkgs>' -A openssl.out)/lib:\$(nix-build --no-out-link '<nixpkgs>' -A leptonica)/lib:\$(nix-build --no-out-link '<nixpkgs>' -A tesseract)/lib:\${LD_LIBRARY_PATH:-}\"
cargo $args"
    else
        cargo "$@"
    fi
}

cd "$ROOT"

# Start from an empty directory so types that were removed or renamed in Rust
# don't leave stale files behind.
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

run_cargo test --lib export_bindings

# Barrel file: re-export every generated type, sorted byte-wise so the output
# does not depend on the locale or on filesystem order.
INDEX="$OUT_DIR/index.ts"
{
    echo "// This file was generated by scripts/generate-ts-bindings.sh. Do not edit this file manually."
    echo
    (cd "$OUT_DIR" && find . -type f -name '*.ts' ! -path './index.ts' | LC_ALL=C sort) |
        while IFS= read -r file; do
            path="${file%.ts}"
            name="$(basename "$path")"
            echo "export type { $name } from '$path';"
        done
} >"$INDEX"

count="$(grep -c '^export type' "$INDEX")"
echo "Generated $count TypeScript types in ${OUT_DIR#"$ROOT"/}"
