#!/usr/bin/env python3
"""The file-length ratchet: no source file may exceed MAX_LINES physical lines.

Run it:
    python3 scripts/lint-file-length.py                  # the gate (CI)
    python3 scripts/lint-file-length.py --list           # every file over the cap
    python3 scripts/lint-file-length.py --emit-baseline  # paste-ready BASELINE

or through mise: `mise run lines` / `lines-check` / `lines-baseline`.

# Why a line cap at all

Length is not a proxy for quality and this gate does not pretend it is. What it
IS a proxy for is the number of things that must be held in the head at once to
change one of them safely. A route module, an OCR pipeline stage or a React
page that no longer fits in one reading is one that stops being reviewable.

# Why *physical* lines

`len(text.splitlines())`. Comments count. Blank lines count. An inline
`#[cfg(test)] mod tests` counts. This is the crudest possible rule and that is
the entire argument for it: every more sophisticated rule needs a comment
scrubber and a string-literal state machine, and each state is a place the count
can be quietly wrong. In a gate, "quietly wrong" resolves to "quietly
permissive". A counter with no states cannot have a state bug.

# Why a BASELINE of frozen counts

readur has a real backlog of long files, so the ones over the cap when this gate
landed are grandfathered as **path -> frozen line count**, forward-only. The
frozen *count* rather than a bare path list is load-bearing: a bare list lets a
grandfathered 1,010-line file grow to 3,000 in silence; a count makes that a
failure. Five conditions, all failures, none advisory:

  new offender  over cap, not in the baseline
  regression    over cap, in the baseline, ABOVE its frozen count
  (pass)        over cap, in the baseline, EXACTLY at its frozen count
  slack         still over the cap but BELOW its frozen number -- the entry was
                not ratcheted when the file shrank, leaving headroom the file
                can grow back into with this gate printing clean
  stale         at or under the cap but still in the baseline -- an entry that
                outlives its fix silently re-permits the next offender there
  unknown       in the baseline but matching no scanned file (renamed/deleted)

A file that improves but stays over the cap MUST update its number in the same
commit that shrank it (`slack`). A file that drops to or under the cap MUST have
its entry deleted (`stale`). Never raise a number to land a change.

# Why Python

It must govern `.ts/.tsx/.css` as well as `.rs`, and it must run without
compiling the crate (readur's build needs tesseract/leptonica system libraries).
The cost: `.py` is not in SOURCE_EXTS, so this gate does not govern itself;
`_self_check` closes that by asserting this file stays under MAX_LINES.

# The over-skip problem

Every condition above is keyed on the baseline, and the baseline is generated by
this same walker, so a file the walker wrongly skips is invisible forever. Two
halves answer that:

  * `_cross_check_against_git` enumerates tracked source files with
    `git ls-files`, an independent source of truth, and fails on any the walker
    dropped without an attributable reason (a walker BUG).
  * It cannot catch a WIDENED exclusion, because "attributable" is decided from
    the same constants the walker skipped with. So
    `scripts/ci/test_lint_file_length.py` pins SKIP_DIRS / SKIP_ROOTS /
    GENERATED as literals, and additionally asserts that no TRACKED governed
    file sits under any SKIP_DIRS component. Widening either fails there.

Ported from AtvikSecurity tyrfing's `scripts/lint-file-length.py`.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

# Inclusive: a file of exactly this many lines is compliant. A round number
# rather than a measured one, because the point is a bright line people can hold
# in their heads, not a percentile.
MAX_LINES = 1000

# Rust and the web frontend. Not TOML, YAML, Markdown, SQL or Helm templates: a
# long config file or a long migration is a list, and a list does not get easier
# to reason about by being cut in half -- whereas everything here describes
# control flow.
SOURCE_EXTS = frozenset({"rs", "ts", "tsx", "js", "jsx", "mjs", "cjs", "css", "scss"})

# Directories never descended into, by basename at any depth. Dependency and
# build trees, plus agent tooling:
#
#   target        cargo output. readur has no source module directory named
#                 `target` (the test suite asserts no tracked source file sits
#                 under any of these names, so adding one fails loudly).
#   node_modules  npm dependencies.
#   dist          vite build output (frontend/dist).
#   .git          the object store.
#   .claude       agent config (tracked files there are Markdown, not source)
#                 and Claude Code worktrees, each a full second copy of the repo.
#   .worktrees    same, for the conventional `git worktree` location.
SKIP_DIRS = frozenset({"target", "node_modules", "dist", ".git", ".claude", ".worktrees"})

# Root-anchored directory skips. None today: docs/ holds real (small) JS/CSS for
# the mkdocs site, and it is governed like everything else.
SKIP_ROOTS: tuple[str, ...] = ()

# Generated artifacts: not hand-written source, so the cap is not a statement
# about them. Entries ending in `/` match a directory prefix; anything else is an
# exact path. None today -- readur commits no generated TS or Rust.
GENERATED: tuple[str, ...] = ()

# Floor on the scan size. Measured at ~480 governed files when this landed; the
# floor sits well below so that deleting a module does not fail it for the wrong
# reason. It catches "walked nothing" (wrong root, SKIP_DIRS swallowing src/),
# nothing finer -- the real over-skip guard is `_cross_check_against_git`.
MIN_SCANNED = 300

# Repo-relative path -> frozen physical line count. Forward-only: ratchet DOWN
# as a file is split, delete the entry when it drops to or under the cap. Never
# raise a number to land a change -- that is the exact regression this blocks.
# Regenerate with `mise run lines-baseline` (it warns about any raised entry).
BASELINE: dict[str, int] = {
    "frontend/src/pages/SourcesPage.tsx": 2761,
    "tests/integration_documents_database_tests.rs": 2702,
    "src/services/webdav/service.rs": 2609,
    "frontend/src/pages/DocumentManagementPage.tsx": 2458,
    "src/ocr/enhanced.rs": 1952,
    "frontend/src/pages/SettingsPage.tsx": 1894,
    "tests/webdav_stress_tests.rs": 1879,
    "src/test_utils.rs": 1774,
    "tests/integration_file_processing_pipeline_tests.rs": 1687,
    "tests/integration_source_sync_cancellation_workflow_tests.rs": 1531,
    "frontend/src/pages/SearchPage.tsx": 1528,
    "src/ocr/xml_extractor.rs": 1429,
    "src/ocr/queue.rs": 1305,
    "frontend/src/services/api.ts": 1226,
    "src/scheduling/source_scheduler.rs": 1153,
    "src/config.rs": 1068,
    "frontend/src/pages/DocumentsPage.tsx": 1112,
    "frontend/src/pages/DebugPage.tsx": 1078,
    "tests/integration_ocrmypdf_strategy_validation_tests.rs": 1037,
}


def _is_build_target(path: Path) -> bool:
    """Is this `target` directory cargo's build output? (sibling Cargo.toml)

    Redundant while `target` is in SKIP_DIRS, and kept so that removing it from
    SKIP_DIRS (should a real `target` module ever appear) stays safe.
    """
    return path.name == "target" and (path.parent / "Cargo.toml").is_file()


def _is_nested_checkout(path: Path) -> bool:
    """Is this directory a separate checkout (worktree, clone, submodule)?

    Anchored on a `.git` entry rather than on a path, so a worktree is skipped
    wherever it lives. `git worktree add` writes `.git` as a FILE; a nested
    clone has it as a directory. `exists()` covers both. It can only hide paths
    untracked HERE, so `git ls-files` never offers them to the cross-check.
    """
    return (path / ".git").exists()


class Finding:
    """One scanned file and its physical line count."""

    __slots__ = ("path", "lines")

    def __init__(self, path: str, lines: int) -> None:
        self.path = path
        self.lines = lines


class Report:
    """Everything wrong with the tree, in the five ways it can be wrong."""

    def __init__(self) -> None:
        self.offenders: list[Finding] = []
        self.regressions: list[tuple[Finding, int]] = []
        self.slack: list[tuple[Finding, int]] = []
        self.stale: list[str] = []
        self.unknown: list[str] = []

    def ok(self) -> bool:
        return not (
            self.offenders or self.regressions or self.slack or self.stale or self.unknown
        )


def evaluate(findings: list[Finding], baseline: dict[str, int]) -> Report:
    """Decide which findings are failures. Pure: no filesystem, no clock.

    `findings` must cover EVERY scanned file, not just the ones over the cap.
    That is what makes `stale` (baselined, present, compliant) distinguishable
    from `unknown` (baselined, absent).
    """
    report = Report()
    seen = set()

    for finding in findings:
        seen.add(finding.path)
        frozen = baseline.get(finding.path)
        if finding.lines > MAX_LINES:
            if frozen is None:
                report.offenders.append(finding)
            elif finding.lines > frozen:
                report.regressions.append((finding, frozen))
            elif finding.lines < frozen:
                report.slack.append((finding, frozen))
        elif frozen is not None:
            report.stale.append(finding.path)

    for path in baseline:
        if path not in seen:
            report.unknown.append(path)

    # Longest first: the reader is deciding what to extract next and wants the
    # worst file at the top. Path breaks ties so the listing is deterministic.
    report.offenders.sort(key=lambda f: (-f.lines, f.path))
    report.regressions.sort(key=lambda pair: (-pair[0].lines, pair[0].path))
    report.slack.sort(key=lambda pair: (-(pair[1] - pair[0].lines), pair[0].path))
    report.stale.sort()
    report.unknown.sort()
    return report


def _ext_of(rel: str) -> str:
    """Lower-cased extension of a repo-relative path, or "" if it has none.

    Case-INSENSITIVE on purpose: macOS and Windows checkouts are, so a `Foo.RS`
    must be governed rather than invisible to both walker and cross-check.
    """
    return rel.rsplit(".", 1)[-1].lower() if "." in rel.rsplit("/", 1)[-1] else ""


def _governed(rel: str) -> bool:
    """Is this repo-relative path one the cap speaks about?"""
    if _ext_of(rel) not in SOURCE_EXTS:
        return False
    if GENERATED and rel.startswith(GENERATED):
        return False
    parts = rel.split("/")
    if parts[0] in SKIP_ROOTS:
        return False
    return not any(p in SKIP_DIRS for p in parts)


def scan(root: Path) -> list[Finding]:
    """Walk `root`, returning one Finding per governed source file.

    Deliberately total rather than fallible: unreadable directories, non-UTF-8
    files and un-stat-able entries are skipped silently. The vacuous-pass risk
    that creates is covered by MIN_SCANNED and `_cross_check_against_git`.
    Symlinks are not followed, so a linked file is never counted twice.
    """
    findings: list[Finding] = []
    _walk(root, root, findings)
    findings.sort(key=lambda f: f.path)
    return findings


def _walk(root: Path, directory: Path, out: list[Finding]) -> None:
    try:
        entries = sorted(directory.iterdir())
    except OSError:
        return

    for entry in entries:
        try:
            if entry.is_symlink():
                continue
            if entry.is_dir():
                if (
                    entry.name in SKIP_DIRS
                    or _is_build_target(entry)
                    or _is_nested_checkout(entry)
                ):
                    continue
                rel_parts = entry.relative_to(root).parts
                if len(rel_parts) == 1 and rel_parts[0] in SKIP_ROOTS:
                    continue
                _walk(root, entry, out)
                continue
            if not entry.is_file():
                continue
        except OSError:
            continue

        # Unix separators everywhere, so a committed baseline path matches on
        # any platform.
        rel = entry.relative_to(root).as_posix()
        if not _governed(rel):
            continue
        try:
            text = entry.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        out.append(Finding(rel, len(text.splitlines())))


def _tracked_files(root: Path) -> list[str] | None:
    """`git ls-files` under root, or None when git is unavailable."""
    try:
        return subprocess.run(
            ["git", "-C", str(root), "ls-files"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.splitlines()
    except (OSError, subprocess.CalledProcessError):
        return None


def _git_required() -> bool:
    """Is the git cross-check mandatory? Yes whenever `CI` is set to a truthy
    value: a CI checkout always has git, so `git ls-files` failing there means
    the backstop silently stopped running, not that this is a tarball."""
    return os.environ.get("CI", "").strip().lower() not in ("", "0", "false", "no")


def _cross_check_against_git(root: Path, findings: list[Finding]) -> list[str]:
    """Tracked source files this walker dropped without an attributable reason.

    Returns an empty list when git is unavailable (a tarball checkout) rather
    than failing -- the check is a backstop, not a dependency. Outside CI only:
    `main` fails the gate when git is unavailable and `_git_required()`.
    """
    tracked = _tracked_files(root)
    if tracked is None:
        return []

    governed_by_walker = {f.path for f in findings}
    unattributed = []
    for rel in tracked:
        if _ext_of(rel) not in SOURCE_EXTS:
            continue
        if rel in governed_by_walker:
            continue
        # Only acceptable if a DECLARED exclusion explains it. Anything else is
        # a walker bug, and this is the only place that can see it.
        if _exclusion_reason(rel) is None:
            unattributed.append(rel)
    return sorted(unattributed)


def _exclusion_reason(rel: str) -> str | None:
    """Which declared exclusion excuses this path, or None if nothing does."""
    if GENERATED and rel.startswith(GENERATED):
        return "generated"
    parts = rel.split("/")
    if parts[0] in SKIP_ROOTS:
        return f"root:{parts[0]}"
    for p in parts:
        if p in SKIP_DIRS:
            return f"dir:{p}"
    return None


def _self_check(root: Path) -> str | None:
    """This gate does not govern its own extension; assert it anyway.

    Fails CLOSED on an unreadable file: "could not check" must never be
    indistinguishable from "passed".
    """
    me = root / "scripts" / "lint-file-length.py"
    try:
        count = len(me.read_text(encoding="utf-8").splitlines())
    except OSError as exc:
        return (
            f"cannot read scripts/lint-file-length.py to check its own length "
            f"({exc}) -- refusing to treat an unreadable self-check as a pass."
        )
    if count > MAX_LINES:
        return (
            f"scripts/lint-file-length.py is {count} lines, over its own "
            f"{MAX_LINES}-line cap. The ratchet must obey the ratchet."
        )
    return None


def _duplicate_baseline_keys(root: Path) -> str | None:
    """Reject a path that appears twice in the BASELINE dict literal.

    A repeated key in a dict literal is not an error in Python -- the LAST value
    silently wins, so pasting a tightened entry above the old one would keep the
    LOOSER number while the diff shows a reduction. Every other check reads the
    evaluated dict and is blind to this; only the source text shows it.
    Fails CLOSED on an unreadable file, as `_self_check` does.
    """
    me = root / "scripts" / "lint-file-length.py"
    try:
        text = me.read_text(encoding="utf-8")
    except OSError as exc:
        return (
            f"cannot read scripts/lint-file-length.py to check BASELINE for "
            f"duplicate keys ({exc}) -- refusing to treat an unreadable "
            "self-check as a pass."
        )

    seen: dict[str, list[int]] = {}
    inside = False
    for raw in text.splitlines():
        if raw.startswith("BASELINE"):
            inside = True
            continue
        if inside and raw == "}":
            break
        if not inside:
            continue
        m = re.match(r'\s*"([^"]+)":\s*(\d+),', raw)
        if m:
            seen.setdefault(m.group(1), []).append(int(m.group(2)))

    dupes = {k: v for k, v in seen.items() if len(v) > 1}
    if not dupes:
        return None
    detail = "".join(
        f"  {path}: {values} -- Python keeps {values[-1]}\n"
        for path, values in sorted(dupes.items())
    )
    return (
        f"{len(dupes)} path(s) appear more than once in BASELINE. A dict "
        "literal keeps only the\nLAST value, so the effective ceiling depends "
        "on line order rather than on the\nnumber anyone intended. Keep one "
        "entry per path and edit its number in place:\n" + detail
    )


def describe(report: Report) -> str:
    """Render a failing report as the message a human acts on."""
    out: list[str] = []

    if report.offenders:
        out.append(
            f"{len(report.offenders)} source file(s) exceed the "
            f"{MAX_LINES}-line cap and are not in the baseline:\n"
        )
        for f in report.offenders:
            out.append(f"  {f.lines:>6}  {f.path}\n")
        out.append(
            "\nSplit them. For a Rust file the first move is almost always to "
            "extract an\ninline `#[cfg(test)] mod tests { .. }` into a sibling "
            "file and leave the\ndeclaration behind -- `use super::*` resolves "
            "identically, so it is a pure move:\n\n"
            "    // in foo.rs\n"
            "    #[cfg(test)]\n"
            '    #[path = "foo_tests.rs"]\n'
            "    mod tests;\n\n"
            "For a React component, lift sub-components, hooks and pure helpers "
            "into sibling\nmodules. Otherwise relocate cohesive code to a "
            "sibling module.\n"
        )

    if report.regressions:
        out.append(
            f"\n{len(report.regressions)} baselined file(s) GREW past their "
            "frozen line count. A baseline\nis a ceiling, not a licence -- "
            "shrink the file rather than raising the number:\n"
        )
        for f, frozen in report.regressions:
            out.append(f"  {f.lines:>6}  (baseline {frozen})  {f.path}\n")

    if report.slack:
        out.append(
            f"\n{len(report.slack)} baseline entr(y/ies) sit ABOVE their file. "
            "Slack is a ratchet with\na free move stored up -- the file can grow "
            "back to the frozen number with this\ngate printing clean. Ratchet "
            "DOWN, in the same commit that shrank the file:\n"
        )
        for f, frozen in report.slack:
            out.append(
                f'    "{f.path}": {f.lines},'
                f"   # was {frozen}, {frozen - f.lines} line(s) of slack\n"
            )

    if report.stale:
        out.append(
            f"\n{len(report.stale)} baseline entr(y/ies) are stale -- the file "
            "is now at or under the\ncap, so the entry must be DELETED. An "
            "entry that outlives its fix silently\nre-permits the next "
            "offender at that path:\n"
        )
        for path in report.stale:
            out.append(f"  {path}\n")

    if report.unknown:
        out.append(
            f"\n{len(report.unknown)} baseline entr(y/ies) name no scanned "
            "source file -- the path does not\nexist, is generated, or is not a "
            "governed extension. Whichever it is, the entry\nprotects nothing. "
            "Delete or repoint them:\n"
        )
        for path in report.unknown:
            out.append(f"  {path}\n")

    return "".join(out)


def _emit_baseline(findings: list[Finding]) -> str:
    over = sorted(
        (f for f in findings if f.lines > MAX_LINES),
        key=lambda f: (-f.lines, f.path),
    )

    # Regenerating wholesale would happily re-freeze a file that GREW --
    # laundering the exact regression `regressions` blocks through a step that
    # looks like routine maintenance. Call those out in the output itself.
    raised = [
        (f, BASELINE[f.path])
        for f in over
        if f.path in BASELINE and f.lines > BASELINE[f.path]
    ]
    lines: list[str] = []
    if raised:
        lines.append(
            f"# WARNING: {len(raised)} entr(y/ies) below are HIGHER than the "
            "committed baseline."
        )
        lines.append(
            "# Pasting this as-is raises a ceiling, which the ratchet forbids. "
            "Shrink the"
        )
        lines.append("# file(s) instead, or paste and then fix them deliberately:")
        for f, was in raised:
            lines.append(f"#   {f.path}: {was} -> {f.lines}")
        lines.append("")

    lines.append("BASELINE: dict[str, int] = {")
    lines += [f'    "{f.path}": {f.lines},' for f in over]
    lines.append("}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--list", action="store_true", help="print every file over the cap")
    parser.add_argument(
        "--emit-baseline",
        action="store_true",
        help="print a paste-ready BASELINE dict",
    )
    args = parser.parse_args(argv)

    root: Path = args.repo.resolve()
    findings = scan(root)

    if args.emit_baseline:
        print(_emit_baseline(findings))
        return 0

    if args.list:
        over = sorted(
            (f for f in findings if f.lines > MAX_LINES),
            key=lambda f: (-f.lines, f.path),
        )
        for f in over:
            frozen = BASELINE.get(f.path)
            mark = "" if frozen is None else f"  (baseline {frozen})"
            print(f"{f.lines:>6}  {f.path}{mark}")
        print(
            f"\n{len(over)} over the {MAX_LINES}-line cap, {len(findings)} scanned",
            file=sys.stderr,
        )
        return 0

    failures: list[str] = []

    if len(findings) < MIN_SCANNED:
        failures.append(
            f"lint-file-length: scan found only {len(findings)} source file(s) "
            f"(expected >= {MIN_SCANNED}) under {root}. The scan root is "
            "likely wrong, or SKIP_DIRS grew broad enough to swallow a source "
            "tree. Refusing to pass vacuously."
        )

    self_check = _self_check(root)
    if self_check:
        failures.append(f"lint-file-length: {self_check}")

    dupes = _duplicate_baseline_keys(root)
    if dupes:
        failures.append(f"lint-file-length: {dupes}")

    if _git_required() and _tracked_files(root) is None:
        failures.append(
            "lint-file-length: `git ls-files` failed while CI is set, so the "
            "cross-check against\ntracked files could not run. Refusing to pass "
            "without it."
        )

    unattributed = _cross_check_against_git(root, findings)
    if unattributed:
        failures.append(
            f"lint-file-length: {len(unattributed)} tracked source file(s) were "
            "dropped by the\nwalker with no attributable reason (not GENERATED, "
            "not under a declared skip).\nA file the walker never enumerates is "
            "invisible to every check in this gate.\nFix the walker, or declare "
            "the exclusion:\n" + "".join(f"  {p}\n" for p in unattributed[:40])
        )

    report = evaluate(findings, BASELINE)
    if not report.ok():
        failures.append(describe(report))

    if failures:
        sys.stderr.write("\n".join(failures))
        # Summarise only the checks that ACTUALLY failed, so a run that failed on
        # MIN_SCANNED does not sign off with a row of reassuring zeros.
        parts = []
        if not report.ok():
            parts.append(f"{len(report.offenders)} new offender(s)")
            parts.append(f"{len(report.regressions)} regression(s)")
            parts.append(f"{len(report.slack)} with slack")
            parts.append(f"{len(report.stale)} stale")
            parts.append(f"{len(report.unknown)} unknown")
        parts.append(f"{len(failures)} check(s) failed")
        sys.stderr.write(
            f"\nlint-file-length FAILED: {', '.join(parts)}, "
            f"out of {len(findings)} file(s) scanned\n"
        )
        return 1

    print(
        f"lint-file-length: {len(findings)} source file(s) scanned, "
        f"{len(BASELINE)} baselined, none over the {MAX_LINES}-line cap"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
