//! The key that signs session tokens. `JWT_SECRET` wins when it is set;
//! otherwise a random key is generated on first start and kept in the
//! database, so every replica and restart uses the same one.

use anyhow::{Context, Result};

use crate::db::Database;

/// Name of the stored signing key in `server_secrets`.
pub const STORED_KEY_NAME: &str = "jwt_signing_key";

/// Random bytes in a generated key (512 bits).
const GENERATED_KEY_BYTES: usize = 64;

/// Where the signing key in use came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SigningKeyOrigin {
    /// `JWT_SECRET`.
    Environment,
    /// A key generated by an earlier start and stored in the database.
    Database,
    /// Generated by this start and stored in the database.
    Generated,
}

impl SigningKeyOrigin {
    /// Startup log text. Never includes the key.
    pub fn describe(self) -> &'static str {
        match self {
            SigningKeyOrigin::Environment => "from JWT_SECRET",
            SigningKeyOrigin::Database => "loaded from database",
            SigningKeyOrigin::Generated => "generated and stored in database",
        }
    }
}

fn generate_key() -> String {
    crate::oidc::random_urlsafe(GENERATED_KEY_BYTES)
}

/// The signing key to use: `configured` (the validated `JWT_SECRET`) when it
/// is non-empty, otherwise the key stored in the database, generating and
/// storing one first if there is none. Requires the migrations to have run.
pub async fn resolve(db: &Database, configured: &str) -> Result<(String, SigningKeyOrigin)> {
    if !configured.is_empty() {
        return Ok((configured.to_string(), SigningKeyOrigin::Environment));
    }
    let (value, inserted) = db
        .get_or_insert_server_secret(STORED_KEY_NAME, &generate_key())
        .await
        .context("Failed to load the stored JWT signing key")?;
    let origin = if inserted { SigningKeyOrigin::Generated } else { SigningKeyOrigin::Database };
    Ok((value, origin))
}
