//! The key that signs session tokens. `JWT_SECRET` wins when it is set;
//! otherwise a random key is generated on first start and kept in the
//! database, so every replica and restart uses the same one.

use anyhow::{Context, Result};

use crate::db::Database;

/// Name of the stored signing key in `server_secrets`.
pub const STORED_KEY_NAME: &str = "jwt_signing_key";

/// Random bytes in a generated key (512 bits).
const GENERATED_KEY_BYTES: usize = 64;

/// Where the signing key in use came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SigningKeyOrigin {
    /// `JWT_SECRET`.
    Environment,
    /// A key generated by an earlier start and stored in the database.
    Database,
    /// Generated by this start and stored in the database.
    Generated,
}

impl SigningKeyOrigin {
    /// Print where the key came from at startup. Only fixed text is printed,
    /// never anything derived from the key.
    pub fn log_startup(self) {
        match self {
            SigningKeyOrigin::Environment => println!("🔐 JWT signing key: from JWT_SECRET"),
            SigningKeyOrigin::Database => println!("🔐 JWT signing key: loaded from database"),
            SigningKeyOrigin::Generated => println!("🔐 JWT signing key: generated and stored in database"),
        }
    }
}

fn generate_key() -> String {
    crate::oidc::random_urlsafe(GENERATED_KEY_BYTES)
}

/// The key stored in the database, generating and storing one first if there
/// is none. Used when `JWT_SECRET` is not set. Requires the migrations to
/// have run.
pub async fn load_or_generate(db: &Database) -> Result<(String, SigningKeyOrigin)> {
    let (value, inserted) = db
        .server_value_or_insert(STORED_KEY_NAME, &generate_key())
        .await
        .context("Failed to load the stored JWT signing key")?;
    let origin = if inserted { SigningKeyOrigin::Generated } else { SigningKeyOrigin::Database };
    Ok((value, origin))
}

/// Replace the stored signing key with a new random one. Tokens signed with
/// the previous key stop verifying once servers load the new key.
pub async fn rotate(db: &Database) -> Result<()> {
    db.replace_server_value(STORED_KEY_NAME, &generate_key())
        .await
        .context("Failed to store a new JWT signing key (has the server been started once to apply migrations?)")
}
